import React from 'react';
import type { Itinerary } from './types';
import { 
    LatamLogoIcon, 
    MaxMilhasLogoIcon,
    AzulLogoIcon,
    DecolarLogoIcon,
    BookingLogoIcon,
    ClickBusLogoIcon,
    CCRBarcasLogoIcon,
    GolLogoIcon,
    TripLogoIcon,
    ExpediaLogoIcon,
    ViajaNetLogoIcon,
    ZupperLogoIcon,
    KiwiLogoIcon,
} from './components/icons';

export const initialItineraries: Itinerary[] = [
  {
    id: 28,
    title: 'Pousada Sakura Rio Mar',
    subtitle: '2 diárias em Ilha Grande (Abraão)',
    savedDate: '2024-07-29 21:00',
    totalPrice: 648.00,
    sourceUrl: 'https://www.booking.com/hotel/br/bella-tulip.pt-br.html',
    events: [
        {
            type: 'accommodation',
            startTime: '14:00',
            endTime: '12:00',
            startDate: '20/12/2025',
            endDate: '22/12/2025',
            startLocation: 'Ilha Grande',
            endLocation: 'Pousada Sakura Rio Mar',
            duration: '2 noites',
            details: '2 adultos',
            company: { name: 'Booking.com', logo: React.createElement(BookingLogoIcon) },
        }
    ]
  },
  {
    id: 27,
    title: 'CCR Barcas: Mangaratiba → Ilha Grande',
    subtitle: 'Passagem só de ida',
    savedDate: '2024-07-28 12:00',
    totalPrice: 20.50,
    sourceUrl: 'http://barcasrio.com.br/linhas_horarios/mangaratiba-ilha-grande/',
    events: [
      {
        type: 'ship',
        startTime: '08:00',
        endTime: '09:50',
        startDate: '20/12',
        endDate: '20/12',
        startLocation: 'Porto de Mangaratiba',
        endLocation: 'Vila do Abraão, Ilha Grande',
        duration: '1h 50m',
        details: 'Operando normalmente',
        company: { name: 'CCR Barcas', logo: React.createElement(CCRBarcasLogoIcon) },
      }
    ]
  },
  {
    id: 14,
    title: 'Azul: Rio de Janeiro → Porto Seguro (18/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-26 17:51',
    totalPrice: 487.00, 
    sourceUrl: 'https://www.google.com/travel/flights/search?tfs=CBwQAhptEgoyMDI1LTEyLTE4IiAKA0dJRxIKMjAyNS0xMi0xOBoDQ05GKgJBRDIENDUwNSIgCgNDTkYSCjIwMjUtMTItMTgaA0JQUyoCQUQyBDI2MDZqDAgCEggvbS8wNmdtcnINCAISCS9tLzAyYmZmOUABSAFwAYIBCwj___________8BmAEC&tfu=CnRDalJJTVdaeFVWVnJhRWhJVUdkQlF5MTBSMmRDUnkwdExTMHRMUzB0TFMxalpYTm5OMEZCUVVGQlIydFlUSEIzVDFobFlqUkJFZzFCUkRRMU1EVjhRVVF5TmpBMkdnc0l1dndDRUFJYUEwSlNURGdjY09CSBIGCAAgAigEIgA&hl=pt-BR&gl=br&curr=BRL',
    events: [
      {
        type: 'flight',
        startTime: '06:10',
        endTime: '16:00',
        startDate: '18/12',
        endDate: '18/12',
        startLocation: 'GIG',
        endLocation: 'BPS',
        duration: '9h 50m',
        details: '1 parada (7h 25m em CNF)',
        company: { name: 'Azul', logo: React.createElement(AzulLogoIcon, { className: "h-10 w-10" }) },
        operator: 'Operado por Azul Linhas Aéreas',
      }
    ],
    baggage: {
      personal: { status: 'Inclusa', details: 'Item pessoal (bolsa ou mochila)' },
      carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
      checked: { status: 'Taxa Adicional', details: 'Bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
        {
            provider: 'Reserve com a Decolar',
            price: 487.00,
            url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
            logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" })
        },
        {
            provider: 'Reserve com a ViajaNet',
            price: 487.00,
            url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
            logo: React.createElement(ViajaNetLogoIcon, { className: "h-10 w-10 p-1" })
        },
        {
            provider: 'Reserve com a Booking.com',
            price: 512.00,
            url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
            logo: React.createElement(BookingLogoIcon, { className: "h-10 w-10 p-1" })
        },
        {
            provider: 'Reserve com a Trip.com',
            price: 535.00,
            url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
            logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" })
        },
        {
            provider: 'Reserve com a maxmilhas',
            price: 638.00,
            url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
            logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } })
        }
    ],
    monitoring: { enabled: true },
    priceHistory: [
      { timestamp: new Date('2025-07-26T17:51:00'), price: 492.00 },
      { timestamp: new Date('2025-07-27T09:00:00'), price: 499.00 },
      { timestamp: new Date('2025-07-28T21:00:00'), price: 580.00 },
      { timestamp: new Date('2025-07-29T21:00:00'), price: 455.00 },
      { timestamp: new Date('2025-07-30T21:00:00'), price: 487.00 },
    ],
  },
  {
    id: 29,
    title: 'LATAM: Rio de Janeiro → Porto Seguro (18/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-30 21:00',
    totalPrice: 537.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTE4IiAKA0dJRxIKMjAyNS0xMi0xOBoDQlBTKgJMQTIEMzAxM2oMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJVFVoRU1Va3hObnBsUjBGQlFrRlpRa0ZDUnkwdExTMHRMUzB0TFdOblluUmxOMEZCUVVGQlIydFlUa0U0UVhSM1YwVkJFZ1pNUVRNd01UTWFDd2p6b2dNUUFob0RRbEpNT0J4d2dFOD0SBggAIAIoBiIA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '23:40',
      endTime: '01:15',
      startDate: '18/12',
      endDate: '19/12',
      startLocation: 'GIG',
      endLocation: 'BPS',
      duration: '1h 35m',
      details: 'Sem escalas',
      company: { name: 'LATAM', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }) },
      operator: 'Operado por Latam Airlines Brasil',
    }],
    baggage: {
      personal: { status: 'Não disponível', details: 'Item pessoal (bolsa ou mochila)' },
      carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
      checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
      {
        provider: 'Reserve com a maxmilhas',
        price: 537.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } })
      },
      {
        provider: 'Reserve com a LATAM',
        price: 580.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }),
        tag: 'Companhia aérea'
      },
      {
        provider: 'Reserve com a Decolar',
        price: 584.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" })
      },
    ],
    monitoring: { enabled: true },
    priceHistory: [
      { timestamp: new Date('2025-07-30T21:00:00'), price: 537.00 },
    ]
  },
   {
    id: 30,
    title: 'GOL: Rio de Janeiro → Porto Seguro (18/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-30 21:00',
    totalPrice: 547.00,
    sourceUrl: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '16:25',
      endTime: '18:00',
      startDate: '18/12',
      endDate: '18/12',
      startLocation: 'GIG',
      endLocation: 'BPS',
      duration: '1h 35m',
      details: 'Sem escalas',
      company: { name: 'GOL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }) },
      operator: 'Operado por GOL Linhas Aéreas',
    }],
    baggage: {
      personal: { status: 'Não disponível', details: 'Informação não disponível' },
      carryOn: { status: 'Taxa Adicional', details: 'Bagagem de mão provavelmente cobrada' },
      checked: { status: 'Taxa Adicional', details: 'Sem bagagem despachada' },
    },
    bookingOptions: [
       {
        provider: 'Reserve com a maxmilhas',
        price: 547.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } })
      },
      {
        provider: 'Reserve com a Zupper',
        price: 574.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(ZupperLogoIcon, { className: "h-10 w-10 p-1" })
      },
      {
        provider: 'Reserve com a Decolar',
        price: 578.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" })
      },
      {
        provider: 'Reserve com a Gol',
        price: 580.00,
        url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE4agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
        logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }),
        tag: 'Companhia aérea'
      },
    ],
    monitoring: { enabled: true },
    priceHistory: [
      { timestamp: new Date('2025-07-30T21:00:00'), price: 547.00 },
    ]
  },
  {
    id: 16,
    title: 'LATAM: Rio de Janeiro → Porto Seguro (20/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 21:00',
    totalPrice: 542.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTIwIiAKA0dJRxIKMjAyNS0xMi0yMBoDQlBTKgJMQTIEMzAxM2oMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJVFVoRU1Va3hObnBsUjBGQlFrSnZSV2RDUnkwdExTMHRMUzB0TFdOblluUmxOMEZCUVVGQlIydFlUbGt3UjJOU2RtZEJFZ1pNUVRNd01UTWFDd2ozcGdNUUFob0RRbEpNT0J4dzRVOD0SBggAIAIoBiIDEgEw&hl=pt-BR&gl=br&curr=BRL',
    events: [
      {
        type: 'flight',
        startTime: '23:40',
        endTime: '01:15',
        startDate: '20/12',
        endDate: '21/12',
        startLocation: 'GIG',
        endLocation: 'BPS',
        duration: '1h 35m',
        details: 'Sem escalas',
        company: { name: 'LATAM', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }) },
        operator: 'Operado por Latam Airlines Brasil',
      }
    ],
    baggage: {
      personal: { status: 'Não disponível', details: 'Item pessoal (bolsa ou mochila)' },
      carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
      checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
        { provider: 'Reserve com a maxmilhas', price: 542.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIwagoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } })},
        { provider: 'Reserve com a LATAM', price: 580.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIwagoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }), tag: 'Companhia aérea' },
        { provider: 'Reserve com a Decolar', price: 590.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIwagoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Trip.com', price: 605.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIwagoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Expedia', price: 663.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIwagoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ExpediaLogoIcon, { className: "h-10 w-10 p-1" }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [
        { timestamp: new Date('2025-07-26T17:48:00'), price: 499.00 },
        { timestamp: new Date('2025-07-31T21:00:00'), price: 542.00 },
    ]
  },
  {
    id: 17,
    title: 'LATAM: Rio de Janeiro → Porto Seguro (19/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 09:00',
    totalPrice: 556.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTE5IiAKA0dJRxIKMjAyNS0xMi0xORoDQlBTKgJMQTIEMzAxM2oMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJTUVaMlZFaHVWbTFMVHpoQlEzcHljMmRDUnkwdExTMHRMUzB0TFMxalpYaGpOa0ZCUVVGQlIydFlUa3haVDNKV01pMUJFZ1pNUVRNd01UTWFDd2pYc1FNUUFob0RRbEpNT0J4dzVWRT0SBggAIAIoBiIA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
        type: 'flight',
        startTime: '23:40',
        endTime: '01:15',
        startDate: '19/12',
        endDate: '20/12',
        startLocation: 'GIG',
        endLocation: 'BPS',
        duration: '1h 35m',
        details: 'Sem escalas',
        company: { name: 'LATAM', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }) },
        operator: 'Operado por Latam Airlines Brasil',
    }],
    baggage: {
        personal: { status: 'Inclusa', details: 'Item pessoal (bolsa ou mochila)' },
        carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
        checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
        { provider: 'Reserve com a maxmilhas', price: 556.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } }) },
        { provider: 'Reserve com a LATAM', price: 580.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }), tag: 'Companhia aérea' },
        { provider: 'Reserve com a Decolar', price: 590.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Trip.com', price: 605.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Expedia', price: 663.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ExpediaLogoIcon, { className: "h-10 w-10 p-1" }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-07-31T09:00:00'), price: 556.00 }],
  },
  {
    id: 31,
    title: 'GOL: Rio de Janeiro → Porto Seguro (19/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 09:00',
    totalPrice: 574.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTE5IiAKA0dJRxIKMjAyNS0xMi0xORoDQlBTKgJHMzIEMTg1MWoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJVUVVeU5sVTJibFJrTmpSQlF6Qk1hRkZDUnkwdExTMHRMUzB0TFMxalpYWmpPRUZCUVVGQlIydFlUbEpSUlZRdE1UUkJFZ1pITXpFNE5URWFDd2lNd0FNUUFob0RRbEpNT0J4d3dWUT0SBggAIAIoBiIA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
        type: 'flight',
        startTime: '15:55',
        endTime: '17:30',
        startDate: '19/12',
        endDate: '19/12',
        startLocation: 'GIG',
        endLocation: 'BPS',
        duration: '1h 35m',
        details: 'Sem escalas',
        company: { name: 'GOL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }) },
        operator: 'Operado por GOL Linhas Aéreas',
    }],
    baggage: {
        personal: { status: 'Não disponível', details: 'Informação não disponível' },
        carryOn: { status: 'Taxa Adicional', details: 'Sem bagagem de mão' },
        checked: { status: 'Taxa Adicional', details: 'Sem bagagem despachada' },
    },
    bookingOptions: [
        { provider: 'Reserve com a Zupper', price: 574.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ZupperLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a ViajaNet', price: 578.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ViajaNetLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Decolar', price: 578.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Gol', price: 580.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }), tag: 'Companhia aérea' },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-07-31T09:00:00'), price: 574.00 }],
  },
  {
    id: 32,
    title: 'LATAM: Rio de Janeiro (SDU) → Porto Seguro (19/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 09:00',
    totalPrice: 620.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTE5IiAKA1NEVRIKMjAyNS0xMi0xORoDQlBTKgJMQTIENDU0MmoMCAISCC9tLzA2Z21ycg0IAhIJL20vMDJiZmY5QAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJUWpVelVsbGhVWGRIZFd0QlF6a3RRV2RDUnkwdExTMHRMUzB0TFMxalpYZG1OVUZCUVVGQlIydFlUbFZKUTA5cE0xTkJFZ1pNUVRRMU5ESWFDd2ozNHdNUUFob0RRbEpNT0J4d29scz0SBggAIAIoBiIA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
        type: 'flight',
        startTime: '12:15',
        endTime: '13:50',
        startDate: '19/12',
        endDate: '19/12',
        startLocation: 'SDU',
        endLocation: 'BPS',
        duration: '1h 35m',
        details: 'Sem escalas',
        company: { name: 'LATAM', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }) },
        operator: 'Operado por Latam Airlines Brasil',
    }],
    baggage: {
        personal: { status: 'Inclusa', details: 'Item pessoal (bolsa ou mochila)' },
        carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
        checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
        { provider: 'Reserve com a LATAM', price: 620.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }), tag: 'Companhia aérea' },
        { provider: 'Reserve com a Kiwi.com', price: 620.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(KiwiLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Decolar', price: 628.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Expedia', price: 691.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ExpediaLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Trip.com', price: 713.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTE5agwIAhIIL20vMDZnbXJyDQgCEgkvbS8wMmJmZjlAAUgBcAGCAQsI____________AZgBAg&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-07-31T09:00:00'), price: 620.00 }],
  },
  {
    id: 21,
    title: 'LATAM: Porto Seguro → Rio de Janeiro (23/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 21:00',
    totalPrice: 338.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTIzIiAKA0JQUxIKMjAyNS0xMi0yMxoDR0lHKgJMQTIEMzc1MmoNCAISCS9tLzAyYmZmOXIMCAISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJVUhGbVYwUnhUak0yYm5kQlF6WkliMUZDUnkwdExTMHRMUzB0TFMxalpYWmlNVUZCUVVGQlIydFlUbWcwUTJkbmVFTkJFZ1pNUVRNM05USWFDd2p0aHdJUUFob0RRbEpNT0J4dzRURT0SBggAIAIoBiIA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '03:35',
      endTime: '05:15',
      startDate: '23/12',
      endDate: '23/12',
      startLocation: 'BPS',
      endLocation: 'GIG',
      duration: '1h 40m',
      details: 'Sem escalas',
      company: { name: 'LATAM', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }) },
      operator: 'Operado por Latam Airlines Brasil',
    }],
    baggage: {
      personal: { status: 'Não disponível', details: 'Item pessoal (bolsa ou mochila)' },
      carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
      checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
      { provider: 'Reserve com a maxmilhas', price: 338.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } }) },
      { provider: 'Reserve com a LATAM', price: 386.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(LatamLogoIcon, { className: "h-10 w-10" }), tag: 'Companhia aérea' },
      { provider: 'Reserve com a Decolar', price: 401.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Expedia', price: 453.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ExpediaLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Trip.com', price: 492.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [
        { timestamp: new Date('2025-07-26T17:54:00'), price: 297.00 },
        { timestamp: new Date('2025-07-31T21:00:00'), price: 338.00 },
    ],
  },
  {
    id: 33,
    title: 'Azul: Porto Seguro → Rio de Janeiro (23/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 21:00',
    totalPrice: 411.00,
    sourceUrl: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '21:00',
      endTime: '00:35',
      startDate: '23/12',
      endDate: '24/12',
      startLocation: 'BPS',
      endLocation: 'GIG',
      duration: '3h 35m',
      details: '1 parada',
      company: { name: 'Azul', logo: React.createElement(AzulLogoIcon, { className: "h-10 w-10" }) },
      operator: 'Operado por Azul Linhas Aéreas',
    }],
    baggage: {
      personal: { status: 'Inclusa', details: 'Item pessoal (bolsa ou mochila)' },
      carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
      checked: { status: 'Taxa Adicional', details: 'Bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
      { provider: 'Reserve com a Decolar', price: 411.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a ViajaNet', price: 411.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ViajaNetLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Booking.com', price: 417.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(BookingLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Trip.com', price: 435.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a maxmilhas', price: 519.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-07-31T21:00:00'), price: 411.00 }],
  },
  {
    id: 34,
    title: 'GOL: Porto Seguro → Rio de Janeiro (23/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-07-31 21:00',
    totalPrice: 449.00,
    sourceUrl: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '18:30',
      endTime: '20:00',
      startDate: '23/12',
      endDate: '23/12',
      startLocation: 'BPS',
      endLocation: 'GIG',
      duration: '1h 30m',
      details: 'Sem escalas',
      company: { name: 'GOL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }) },
      operator: 'Operado por GOL Linhas Aéreas',
    }],
    baggage: {
        personal: { status: 'Não disponível', details: 'Informação não disponível' },
        carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
        checked: { status: 'Taxa Adicional', details: 'Sem bagagem despachada' },
    },
    bookingOptions: [
      { provider: 'Reserve com a Gol', price: 449.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }), tag: 'Companhia aérea' },
      { provider: 'Reserve com a Decolar', price: 451.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a ViajaNet', price: 451.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ViajaNetLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Trip.com', price: 528.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTIzagoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-07-31T21:00:00'), price: 449.00 }],
  },
  {
    id: 35,
    title: 'Azul: Porto Seguro → Rio de Janeiro (24/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-08-01 11:48',
    totalPrice: 316.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhptEgoyMDI1LTEyLTI0IiAKA0JQUxIKMjAyNS0xMi0yNBoDQ05GKgJBRDIEMjYyNiIgCgNDTkYSCjIwMjUtMTItMjQaA0dJRyoCQUQyBDQxMTBqDQgCEgkvbS8wMmJmZjlyDAgCEggvbS8wNmdtckABSAFwAYIBCwj___________8BmAEC&tfu=CnRDalJJWlRWc2FVSmZWVm8yTURCQlEzbDVlVUZDUnkwdExTMHRMUzB0WTJWaVltc3hNa0ZCUVVGQlIydFlVVlJGUzJOTU1uVkJFZzFCUkRJMk1qWjhRVVEwTVRFd0dnc0kxZllCRUFJYUEwSlNURGdjY0w0dRIGCAAgAigGIgA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '16:30',
      endTime: '00:35',
      startDate: '24/12',
      endDate: '25/12',
      startLocation: 'BPS',
      endLocation: 'GIG',
      duration: '8h 5m',
      details: '1 parada (5h 45m em CNF)',
      company: { name: 'Azul', logo: React.createElement(AzulLogoIcon, { className: "h-10 w-10" }) },
      operator: 'Operado por Azul Linhas Aéreas',
    }],
    baggage: {
        personal: { status: 'Não disponível', details: 'Item pessoal' },
        carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
        checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
      { provider: 'Reserve com a Decolar', price: 316.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a ViajaNet', price: 316.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ViajaNetLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Booking.com', price: 321.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(BookingLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a Trip.com', price: 336.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
      { provider: 'Reserve com a maxmilhas', price: 372.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-08-01T11:48:00'), price: 316.00 }],
  },
  {
    id: 36,
    title: 'Azul: Porto Seguro → Rio de Janeiro (SDU) (24/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-08-01 11:48',
    totalPrice: 343.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhptEgoyMDI1LTEyLTI0IiAKA0JQUxIKMjAyNS0xMi0yNBoDQ05GKgJBRDIEMjYyNiIgCgNDTkYSCjIwMjUtMTItMjQaA1NEVSoCQUQyBDQwMTRqDQgCEgkvbS8wMmJmZjlyDAgCEggvbS8wNmdtckABSAFwAYIBCwj___________8BmAEC&tfu=CnRDalJJYzNwelRUazFWV3hqVUdOQlFtbFVURUZDUnkwdExTMHRMUzB0TFhscGNIRXhNVUZCUVVGQlIydFlVVmx6U2taYWREUkJFZzFCUkRJMk1qWjhRVVEwTURFMEdnc0luSXNDRUFJYUEwSlNURGdjY0s0eRIGCAAgAigGIgA&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '16:30',
      endTime: '20:25',
      startDate: '24/12',
      endDate: '24/12',
      startLocation: 'BPS',
      endLocation: 'SDU',
      duration: '3h 55m',
      details: '1 parada (1h 35m em CNF)',
      company: { name: 'Azul', logo: React.createElement(AzulLogoIcon, { className: "h-10 w-10" }) },
      operator: 'Operado por Azul Linhas Aéreas',
    }],
    baggage: {
        personal: { status: 'Não disponível', details: 'Item pessoal' },
        carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
        checked: { status: 'Taxa Adicional', details: 'Uma bagagem despachada cobrada à parte' },
    },
    bookingOptions: [
        { provider: 'Reserve com a Decolar', price: 343.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a ViajaNet', price: 343.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ViajaNetLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Booking.com', price: 346.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(BookingLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Trip.com', price: 363.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(TripLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a maxmilhas', price: 380.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-08-01T11:48:00'), price: 343.00 }],
  },
  {
    id: 37,
    title: 'GOL: Porto Seguro → Rio de Janeiro (24/12)',
    subtitle: 'Só Ida · Econômica · 1 passageiro',
    savedDate: '2024-08-01 11:48',
    totalPrice: 410.00,
    sourceUrl: 'https://www.google.com/travel/flights/booking?tfs=CBwQAhpLEgoyMDI1LTEyLTI0IiAKA0JQUxIKMjAyNS0xMi0yNBoDR0lHKgJHMzIEMjA0OWoNCAISCS9tLzAyYmZmOXIMCAISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=CmxDalJJWkhoRlNXcFlaSEpNV0ZWQlFqZGtOM2RDUnkwdExTMHRMUzB0ZVdsaVltTXlPRUZCUVVGQlIydFlVV3RGUzJScmNWVkJFZ1pITXpJd05Ea2FDd2lsd0FJUUFob0RRbEpNT0J4d3Jqdz0SBggAIAIoBiIDCgEw&hl=pt-BR&gl=br&curr=BRL',
    events: [{
      type: 'flight',
      startTime: '16:05',
      endTime: '17:40',
      startDate: '24/12',
      endDate: '24/12',
      startLocation: 'BPS',
      endLocation: 'GIG',
      duration: '1h 35m',
      details: 'Sem escalas',
      company: { name: 'GOL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }) },
      operator: 'Operado por GOL Linhas Aéreas',
    }],
    baggage: {
        personal: { status: 'Não disponível', details: 'Informação não disponível' },
        carryOn: { status: 'Inclusa', details: '1 bagagem de mão incluída' },
        checked: { status: 'Taxa Adicional', details: 'Sem bagagem despachada' },
    },
    bookingOptions: [
        { provider: 'Reserve com a maxmilhas', price: 410.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(MaxMilhasLogoIcon, { className: "h-10 w-10 p-1", style: { borderRadius: '8px' } }) },
        { provider: 'Reserve com a Zupper', price: 447.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(ZupperLogoIcon, { className: "h-10 w-10 p-1" }) },
        { provider: 'Reserve com a Gol', price: 449.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(GolLogoIcon, { className: "h-10 w-10 p-1" }), tag: 'Companhia aérea' },
        { provider: 'Reserve com a Decolar', price: 451.00, url: 'https://www.google.com/travel/flights/search?tfs=CBwQAhopEgoyMDI1LTEyLTI0agoMCAISCS9tLzAyYmZmOXINCgISCC9tLzA2Z21yQAFIAXABggELCP___________wGYAQI&tfu=EgYIACACKAQiAA&hl=pt-BR&gl=br&curr=BRL', logo: React.createElement(DecolarLogoIcon, { className: "h-10 w-10 p-1" }) },
    ],
    monitoring: { enabled: true },
    priceHistory: [{ timestamp: new Date('2025-08-01T11:48:00'), price: 410.00 }],
  },
  {
    id: 26,
    title: 'ClickBus: Rio de Janeiro → Paraty',
    subtitle: 'Ida e Volta · Semi-Leito · 1 passageiro',
    savedDate: '2024-07-28 10:00',
    totalPrice: 215.80,
    sourceUrl: 'https://www.clickbus.com.br/',
    events: [
      {
        type: 'bus',
        startTime: '08:00',
        endTime: '12:30',
        startDate: '20/12',
        endDate: '20/12',
        startLocation: 'Rodoviária Novo Rio',
        endLocation: 'Rodoviária de Paraty',
        duration: '4h 30m',
        details: 'Viação Costa Verde',
        company: { name: 'ClickBus', logo: React.createElement(ClickBusLogoIcon, { className: "h-8 w-auto" }) },
      },
      {
        type: 'bus',
        startTime: '14:00',
        endTime: '18:30',
        startDate: '24/12',
        endDate: '24/12',
        startLocation: 'Rodoviária de Paraty',
        endLocation: 'Rodoviária Novo Rio',
        duration: '4h 30m',
        details: 'Viação Costa Verde',
        company: { name: 'ClickBus', logo: React.createElement(ClickBusLogoIcon, { className: "h-8 w-auto" }) },
      }
    ]
  }
];